#!/usr/bin/env node

/**
 * Char Setup Helper
 *
 * Utilities for verifying Char installation and configuration.
 * Run from the skill directory.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Replace API key placeholder in demo HTML
 */
export async function injectApiKey(htmlPath, apiKey) {
  const content = await readFile(htmlPath, 'utf-8');

  if (!apiKey || !apiKey.startsWith('sk-ant-')) {
    throw new Error('Invalid Anthropic API key. Must start with "sk-ant-"');
  }

  const updated = content.replaceAll(
    'REPLACE_WITH_API_KEY',
    apiKey
  );

  await writeFile(htmlPath, updated, 'utf-8');

  return {
    success: true,
    path: htmlPath,
    message: `API key injected into ${htmlPath}`
  };
}

/**
 * Verify demo HTML has required structure
 */
export async function verifyDemoPage(htmlPath) {
  const content = await readFile(htmlPath, 'utf-8');

  const checks = {
    hasEmbeddedAgent:
      content.includes('@mcp-b/char') || content.includes('cdn.jsdelivr.net/npm/@mcp-b/char'),
    hasApiKey: !content.includes('REPLACE_WITH_API_KEY'),
    hasStyles: content.includes('<style>') || content.includes('styles.css'),
    hasWebComponent: content.includes('<char-agent'),
  };

  const allPassed = Object.values(checks).every(Boolean);

  return {
    success: allPassed,
    checks,
    message: allPassed
      ? 'Demo page is properly configured'
      : 'Demo page is missing required elements'
  };
}

/**
 * Extract form fields from HTML for testing
 */
export async function extractFormFields(htmlPath) {
  const content = await readFile(htmlPath, 'utf-8');

  // Simple regex to find input/select/textarea elements
  const inputRegex = /<(input|select|textarea)[^>]*id=["']([^"']+)["'][^>]*>/g;
  const fields = [];

  let match;
  while ((match = inputRegex.exec(content)) !== null) {
    const [, type, id] = match;
    fields.push({ type, id });
  }

  return fields;
}

/**
 * Generate test data for forms
 */
export function generateTestData(fields) {
  const testData = {};

  for (const field of fields) {
    switch (field.id) {
      case 'name':
        testData[field.id] = 'Test User';
        break;
      case 'email':
        testData[field.id] = 'test@example.com';
        break;
      case 'phone':
        testData[field.id] = '555-1234';
        break;
      case 'message':
        testData[field.id] = 'This is a test message generated by Char setup.';
        break;
      case 'topic':
        testData[field.id] = 'general';
        break;
      default:
        testData[field.id] = `test-${field.id}`;
    }
  }

  return testData;
}

/**
 * Create a simple test script
 */
export function generateTestScript(fields) {
  const testData = generateTestData(fields);

  return `
// Char Setup Test Script
// This script verifies WebMCP tools are working

async function testCharSetup() {
  console.log('🧪 Starting Char setup test...');

  // Test 1: Take snapshot
  console.log('📸 Taking page snapshot...');
  const snapshot = await webmcp.takeSnapshot();
  console.log('✅ Snapshot taken:', snapshot.elements.length, 'elements found');

  // Test 2: Fill form fields
  console.log('📝 Filling form fields...');
  ${fields.map(f => `  await webmcp.fill({ uid: '${f.id}', value: '${testData[f.id]}' });`).join('\n')}
  console.log('✅ Form filled');

  // Test 3: Take screenshot
  console.log('📷 Taking screenshot...');
  await webmcp.takeScreenshot({ filePath: '/tmp/char-test.png' });
  console.log('✅ Screenshot saved to /tmp/char-test.png');

  console.log('🎉 All tests passed! Char setup is working correctly.');
}

testCharSetup().catch(console.error);
`;
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const command = process.argv[2];
  const arg1 = process.argv[3];
  const arg2 = process.argv[4];

  try {
    switch (command) {
      case 'inject-key':
        const result = await injectApiKey(arg1, arg2);
        console.log(result.message);
        break;

      case 'verify':
        const verification = await verifyDemoPage(arg1);
        console.log(verification.message);
        console.log(verification.checks);
        break;

      case 'extract-fields':
        const fields = await extractFormFields(arg1);
        console.log('Form fields:', fields);
        break;

      case 'generate-test':
        const testFields = await extractFormFields(arg1);
        const script = generateTestScript(testFields);
        console.log(script);
        break;

      default:
        console.log('Usage:');
        console.log('  node setup.js inject-key <html-path> <api-key>');
        console.log('  node setup.js verify <html-path>');
        console.log('  node setup.js extract-fields <html-path>');
        console.log('  node setup.js generate-test <html-path>');
    }
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}
